# Texte der Website, wortgleich aus MJOAR_WEB_COPY_v3.md (Fable, 07.10.2026). Markierung **…** = fett im Original.
# [BILD …]-Hinweise der Copy sind Regieanweisungen und stehen nicht hier. Nicht in der Copy stehen nur die Einträge in
# NICHT_IN_COPY (Bedienetiketten, Alt-Texte, EN-Abschnittstitel); sie werden im PR zur Freigabe gelistet.

T = {
    "de": {
        "menu": ["LUN Milchkännchen", "Milch und Latte Art", "Über uns"],
        "sprachen": ["Deutsch", "English"],
        "kaufen": "Kaufen",
        "kaufzeile": "Bestellung und Versand über Amazon",
        "kaufzeile_lang": "Bestellung und Versand über Amazon. Rückgabe und Gewährleistung wie bei jeder Bestellung dort.",
        # A Fuß
        "fuss_links": "**MJØÅR.** Schöne Dinge für deine Kaffee-Ecke. Aus München und Wien.",
        "fuss_mitte": "Fragen zu deiner LUN? Schreib uns, wir antworten selbst. info@mjoar.com",
        "nl": "**Neu bei MJØÅR, per Mail.** Selten. Neue Produkte, Anleitungen, sonst nichts.",
        "nl_feld": "E-Mail",
        "nl_knopf": "Eintragen",
        "nl_klein": ("Erst kommt eine Bestätigungsmail. Abmelden mit einem Klick. Details im ", "Datenschutz", "."),
        "unten": ["Impressum", "Datenschutz", "Sicherheitshinweise (PDF)"],
        # B Startseite
        "hero_dach": "LUN 350 · MILCHKÄNNCHEN",
        "hero_h": "Die Kanne neben deiner Maschine.",
        "hero_p": "Ein Millimeter Edelstahl, eine Tülle für Latte Art, matte Farben. Gemacht, um jeden Morgen benutzt zu werden, und schön genug, um stehen zu bleiben.",
        "hero_link": "Die LUN ansehen",
        "farben_h": "Vier ruhige Farben.",
        "farben_unter": "Alle matt.",
        "farben": {"juniper": ("Juniper", "Grün, matt"), "linen": ("Linen", "Cremeweiß, matt"), "onyx": ("Onyx", "Schwarz, matt"), "steel": ("Steel", "Edelstahl, gebürstet")},
        "farben_p": "Polierter Edelstahl spiegelt jedes Licht und jeden Fingerabdruck. Wir wollten das Gegenteil. Drei Farben mit matter Beschichtung, dazu Steel aus Edelstahl, fein gebürstet statt poliert. Neben einer Maschine aus Chrom wird die LUN dadurch nicht zum zweiten Spiegel. Sie wird zum Ruhepunkt.",
        "farbe_link": "{} ansehen",
        "vier_h": "Vier Dinge, über die wir lange nachgedacht haben.",
        "vier": [
            ("Die Tülle.", "Schmal, mit runder Kante. Sie gibt die Milch in einem ruhigen Strahl ab und hört sauber auf, wenn du die Kanne anhebst. Für ein Herz reicht das. Für eine Rosetta auch, mit etwas Übung.", "detail-ausguss"),
            ("Ein Millimeter Edelstahl.", "Dünnes Blech gibt nach, wenn du die Kanne festhältst, und wird schnell heiß. Die LUN nicht. Sie liegt schwer genug in der Hand, um ruhig zu gießen, und hält das Klopfen auf der Arbeitsplatte aus, mit dem die großen Blasen verschwinden.", "detail-wand"),
            ("Die Skala innen.", "Lasergraviert in ml und oz. Kein Aufkleber, nichts, das sich in der Spülmaschine löst. Du siehst die Menge, bevor der Dampf angeht.", "detail-skala"),
            ("Der Griff ohne Naht.", "Er geht in den Korpus über, ohne sichtbare Schweißpunkte. Da sitzt keine Kante, an der Milch eintrocknet. Und an den Fingern fühlt es sich an wie ein Stück.", "detail-griff"),
        ],
        "groesse_h": "350 Milliliter. Mit Absicht nicht mehr.",
        "groesse_p": "Milch wächst beim Schäumen. Deshalb fasst die LUN mehr, als am Ende in die Tasse geht. Genug für einen Latte, einen Cappuccino, einen Matcha Latte oder zwei Flat Whites. Für eine Kanne, die jeden Morgen benutzt wird, ist das die richtige Größe. Klein genug, um ruhig zu gießen. Groß genug für zwei.",
        "gebrauch_h": "Zischen, wirbeln, gießen.",
        "gebrauch_p": "Kalte Milch, kalte Kanne. Dampf an, ein leises Zischen, dann dreht sich die Milch. Sobald der Korpus zu warm zum Halten wird, ist sie fertig. Du spürst es an der Hand, nicht am Griff. Einmal klopfen, schwenken, bis sie glänzt. Dann gießen.",
        "gebrauch_link": "Schritt für Schritt: Milch und Latte Art",
        "pflege_h": "Spülmaschine? Ja.",
        "pflege_p": "Alle vier Farben dürfen hinein, an Tagen, an denen es schnell gehen muss. Wer sie mag, spült sie von Hand und trocknet sie kurz ab. So bleibt die Oberfläche am längsten frei von Wasserflecken.",
        "wer_dach": "MÜNCHEN · WIEN",
        "wer_h": "Zwei Leute, eine Siebträgermaschine pro Küche.",
        "wer_p": "MJØÅR sind Thorsten und Jonah, Vater und Sohn. Thorsten lebt in München, Jonah in Wien, und am Wochenende steht Jonah hinter der Theke eines Wiener Cafés. Dort war die LUN einige Wochen im Einsatz, bevor wir sie verkauft haben.",
        "wer_link": "Wie die LUN entstanden ist",
        "aus_h": "Karton, Baumwolle, Kanne. Kein Plastik dazwischen.",
        "aus_p": "Die LUN kommt in einem Naturkarton mit Siegel, darin ein Beutel aus Baumwolle. Das macht sie zu einem guten Geschenk. Und wenn sie bei dir bleibt, hat der Beutel danach noch einen Job.",
        "ausblick": "Als Nächstes: Gläser und Tassen. Wir arbeiten daran.",
        # C Produktseite
        "dach": "LUN · MILCHKÄNNCHEN · 350 ML",
        "titel": "LUN 350",
        "absatz": "Ein Milchkännchen aus einem Millimeter Edelstahl, mit schmaler Tülle für Latte Art und einer Skala innen. Alle vier matt, Steel als gebürsteter Edelstahl.",
        "punkte": ["Tülle für Herz, Tulpe, Rosetta", "Skala innen, ml und oz, lasergraviert", "Spülmaschinengeeignet, alle Farben"],
        "farbwahl": "Farbe",
        "detail": [
            ("Die Tülle.", "Bei Latte Art entscheidet nicht die Maschine, sondern die letzte Zentimeterstrecke zwischen Kanne und Tasse. Die Tülle der LUN ist schmal und vorne rund gezogen. Die Milch läuft als ruhiger Faden statt als Schwall. Hältst du die Tülle nah an die Oberfläche, legt sich die Milch obenauf. Ziehst du sie am Ende hoch, reißt der Strahl sauber ab. Mehr braucht ein Herz nicht.", "detail-ausguss"),
            ("Die Wand.", "Ein Millimeter Edelstahl 304, für die ganze Kanne, auch den Griff. Viele Kannen in dieser Größe sind dünner. Man merkt es, wenn man sie fest anfasst. Die LUN gibt nicht nach. Sie hat etwas Gewicht, und das hilft beim Gießen, weil die Hand weniger zittert. Wenn du die Kanne nach dem Aufschäumen auf die Arbeitsplatte klopfst, damit die großen Blasen platzen, klingt das satt statt blechern.", "detail-wand"),
            ("Die Wärme.", "Edelstahl leitet Wärme. Das ist hier ein Vorteil: Am Korpus spürst du, wie heiß die Milch gerade ist. Ist er zu warm zum Halten, ist sie fertig. Der Griff bleibt dabei angenehm.", "gebrauch-aufschaeumen"),
            ("Die Skala.", "Innen lasergraviert, in Milliliter und Unzen. Sie hilft beim Wiederholen: gleiche Menge, gleiches Ergebnis. Und weil sie im Stahl sitzt, übersteht sie jede Spülmaschine.", "detail-skala"),
            ("Die Oberfläche.", "Juniper, Linen und Onyx sind matt beschichtet. Steel ist fein gebürsteter Edelstahl. Beides zeigt deutlich weniger Fingerabdrücke als polierter Edelstahl, und beides wirkt neben einer Maschine ruhiger.", "detail-griff"),
        ],
        "entstehung_h": "Drei Musterrunden. Eine Farbe weniger.",
        "entstehung_p": "Zuerst ging es um die Farben. Dann um die Spülmaschine, weil eine schöne Beschichtung nichts wert ist, wenn sie nach ein paar Wochen nachlässt. Ein blaues Muster hat diesen Test nicht gut überstanden. Deshalb gibt es kein Blau. Danach war die LUN einige Wochen im Café-Alltag in Wien, bei Jonah hinter der Theke. Zum Schluss kam die Verpackung, ohne Plastik.",
        "daten_h": "Daten",
        "daten": [("Inhalt", "350 ml"), ("Material", "Edelstahl 304, ganze Kanne"), ("Wandstärke", "1 mm"),
                  ("Oberfläche", "Juniper, Linen, Onyx matt beschichtet; Steel gebürstet"), ("Skala", "innen, lasergraviert, ml und oz"),
                  ("Höhe / Ø oben / Ø unten", "9,3 / 6,4 / 7,5 cm"), ("Gewicht", "198 g"), ("Spülmaschine", "ja, alle Farben"),
                  ("Herd, Induktion, Mikrowelle", "nein"), ("Lebensmittelkontakt", None)],
        "lfgb_platzhalter": "folgt",
        "daten_klein": "Von Hand gemessen, kleine Abweichungen sind möglich.",
        "box_h": "In der Box und Pflege",
        "box": [("In der Box:", "die LUN im Baumwollbeutel, im Naturkarton mit Siegel. Kein Plastik."),
                ("Pflege:", "Spülmaschinengeeignet. Von Hand gespült und abgetrocknet bleibt die Oberfläche am längsten ohne Wasserflecken. Keine Scheuermittel, keine Stahlwolle.")],
        "pdf_zeile": "Sicherheitshinweise als PDF:",
        "pdf_link": "Sicherheitshinweise (PDF)",
        "fragen_h": "Fragen",
        "fragen": [
            ("Darf die LUN in die Spülmaschine?", "Ja, alle vier Farben. Von Hand gespült und kurz abgetrocknet bleibt sie am längsten schön."),
            ("Wie viel passt hinein?", "350 ml. Das reicht für einen Latte, einen Cappuccino, einen Matcha Latte oder zwei Flat Whites, weil Milch beim Schäumen Platz braucht."),
            ("Klappt das auch mit Haferdrink?", "Ja. Barista-Varianten von Hafer- oder Sojadrink schäumen am stabilsten."),
            ("Wird der Griff heiß?", "Die Wärme spürst du am Korpus, der Griff bleibt angenehm."),
            ("Kann ich darin Milch erhitzen?", "Nein. Nicht auf den Herd, nicht auf Induktion, nicht in die Mikrowelle. Die LUN ist zum Aufschäumen unter der Dampflanze gemacht."),
            ("Warum kein Blau?", "Ein blaues Muster hat unsere Spülmaschinentests nicht gut überstanden."),
            ("Woher kommt der Name?", "Aus mjølk, norwegisch für Milch, und å, dem Wort für einen kleinen Fluss. Milch, die fließt. Wie beim Gießen."),
        ],
        "schluss": ("Viel Freude mit deiner LUN.", "Thorsten und Jonah"),
        # D Milch und Latte Art
        "la_dach": "KLEINE KAFFEEKUNDE",
        "la_h": "Milch und Latte Art.",
        "la_intro": "Gute Milch für Latte Art sieht aus wie nasse Farbe. Glänzend, fein, ohne sichtbare Blasen. Dahin kommst du in fünf Schritten. Der Rest ist Übung, und die macht man am besten jeden Morgen.",
        "la_schritte": [
            ("Kalt anfangen.", "Kalte Milch, gern auch eine kalte Kanne. Je mehr Zeit die Milch beim Erwärmen hat, desto feiner wird der Schaum. Füll nicht zu voll. Die Milch braucht Platz nach oben."),
            ("Luft ziehen.", "Die Dampflanze knapp unter die Oberfläche, Dampf auf. Ein leises, gleichmäßiges Zischen heißt: Es kommt Luft hinein. Nur ein paar Sekunden. Klingt es wie Reißen, ist die Lanze zu weit oben."),
            ("Wirbeln.", "Lanze etwas tiefer, Kanne leicht schräg. Die Milch beginnt sich zu drehen und zieht die großen Blasen nach unten, wo sie zerfallen. Leg die Hand an den Korpus. Wird er zu warm zum Halten, Dampf aus."),
            ("Klopfen und schwenken.", "Einmal kurz auf die Arbeitsplatte, damit letzte Blasen platzen. Dann die Kanne kreisen lassen, bis die Oberfläche glänzt wie Lack."),
            ("Gießen.", "Erst aus etwas Höhe in die Mitte der Tasse, damit sich Milch und Espresso verbinden. Dann nah ran, die Tülle fast auf der Oberfläche. Jetzt bleibt die Milch oben und das Muster entsteht. Zum Schluss anheben und einmal durchziehen."),
        ],
        "la_fehler_h": "Häufige Fehler:",
        "la_fehler": [("Große Blasen?", "Zu viel Luft oder zu spät gewirbelt."), ("Milch versinkt?", "Tülle zu weit oben."),
                      ("Muster verläuft?", "Milch zu dünn, beim nächsten Mal etwas länger Luft ziehen.")],
        "la_schluss": "Das erste Herz wird selten schön. Das zehnte schon eher.",
        "la_drei_h": "Drei Getränke, eine Kanne",
        "la_drei": [("Flat White:", "doppelter Espresso, wenig, sehr feine Milch. Aus der LUN reicht es für zwei."),
                    ("Cappuccino:", "mehr Schaum, gleiche Tasse. Eine LUN, ein Cappuccino."),
                    ("Matcha Latte:", "Matcha mit etwas heißem Wasser glatt rühren, dann aufgeschäumte Milch darüber. Funktioniert genauso mit Kakao.")],
        # E Über uns
        "ueber_dach": "MÜNCHEN · WIEN",
        "ueber_h": "Thorsten und Jonah.",
        "ueber_p": [
            "Vater und Sohn. Thorsten ist in Wien aufgewachsen und lebt in München. Jonah ist in München aufgewachsen und lebt in Wien. Bei beiden beginnt der Tag an einer Siebträgermaschine, und auf Reisen ist das erste Ziel meistens ein Café.",
            "Die Kannen, die wir kannten, sahen nach Werkzeug aus. Dünnes Blech, Schweißpunkte am Griff, Hochglanz wie in einer Großküche. Neben einer schönen Maschine haben sie nie gepasst. Also haben wir eine gezeichnet, die das tut.",
            "Drei Musterrunden später, nach einigen Wochen im Café-Alltag in Wien und einer Verpackung ganz ohne Plastik, gab es die LUN. Den Namen MJØÅR haben wir aus zwei Wörtern gebaut: mjølk, norwegisch für Milch, und å, ein kleiner Fluss. Skandinavisch klingt er. Gemacht ist er für Küchen in München, Wien und überall sonst.",
            "Wir entwerfen Dinge für Kaffee, Matcha und Kakao. Mit gutem Material, zu einem fairen Preis, schön genug zum Verschenken. Als Nächstes kommen Gläser und Tassen.",
            "MJØÅR ist klein. Das heißt: Wenn du schreibst, antworten wir selbst. info@mjoar.com",
        ],
        # F Meta
        "meta": {
            "start": ("MJØÅR · LUN Milchkännchen aus Edelstahl", "Die LUN 350: ein Millimeter Edelstahl, Tülle für Latte Art, matte Farben. Von Thorsten und Jonah aus München und Wien."),
            "lun": ("LUN 350 Milchkännchen · MJØÅR", "350 ml, Skala innen, spülmaschinengeeignet. In Juniper, Linen, Onyx und Steel."),
            "latte": ("Milch schäumen und Latte Art · MJØÅR", "Fünf Schritte zu glänzender Milch und dem ersten Herz. Dazu Flat White, Cappuccino und Matcha Latte."),
            "ueber": ("Über uns · MJØÅR", "Thorsten und Jonah, Vater und Sohn aus München und Wien, und wie die LUN entstanden ist."),
            "impressum": ("Impressum · MJØÅR", None),
            "datenschutz": ("Datenschutz · MJØÅR", None),
        },
    },
    "en": {
        "menu": ["LUN milk jug", "Milk and latte art", "About"],
        "sprachen": ["Deutsch", "English"],
        "kaufen": "Buy",
        "kaufzeile": "Ordered and shipped via Amazon",
        "kaufzeile_lang": "Ordered and shipped via Amazon. Returns and warranty as with any order there.",
        "fuss_links": "**MJØÅR.** Beautiful things for your coffee corner. From Munich and Vienna.",
        "fuss_mitte": "Questions about your LUN? Write to us and we'll answer ourselves. info@mjoar.com",
        "nl": "**New from MJØÅR, by email.** Rarely. New products, guides, nothing else.",
        "nl_feld": "Email",
        "nl_knopf": "Sign up",
        "nl_klein": ("A confirmation email comes first. Unsubscribe in one click. Details in our ", "privacy policy", "."),
        "unten": ["Imprint", "Privacy", "Safety information (PDF)"],
        "hero_dach": "LUN 350 · MILK JUG",
        "hero_h": "The jug next to your machine.",
        "hero_p": "One millimetre of stainless steel, a spout for latte art, matt colours. Built to be used every morning, and good-looking enough to stay out on the counter.",
        "hero_link": "See the LUN",
        "farben_h": "Four calm colours.",
        "farben_unter": "All matt.",
        "farben": {"juniper": ("Juniper", "green, matt"), "linen": ("Linen", "cream, matt"), "onyx": ("Onyx", "black, matt"), "steel": ("Steel", "brushed stainless steel")},
        "farben_p": "Polished steel catches every light and every fingerprint. We wanted the opposite. Three colours with a matt coating, plus Steel in stainless steel, finely brushed instead of polished. Next to a chrome machine, the LUN doesn't become a second mirror. It becomes the calm spot.",
        "farbe_link": "See {}",
        "vier_h": "Four things we thought about for a long time.",
        "vier": [
            ("The spout.", "Narrow, with a rounded edge. It lets the milk out in a steady stream and stops cleanly when you lift the jug. Enough for a heart. Enough for a rosetta too, with a bit of practice.", "detail-ausguss"),
            ("One millimetre of steel.", "Thin metal flexes when you grip it and heats up fast. The LUN doesn't. It's heavy enough in the hand to pour calmly, and it takes the tapping on the worktop that knocks out the big bubbles.", "detail-wand"),
            ("The scale inside.", "Laser engraved in ml and oz. No sticker, nothing to peel off in the dishwasher. You see the amount before the steam goes on.", "detail-skala"),
            ("The handle without a seam.", "It runs into the body with no visible weld points. No edge for milk to dry in. And under your fingers it feels like one piece.", "detail-griff"),
        ],
        "groesse_h": "350 millilitres. Deliberately no more.",
        "groesse_p": "Milk grows as you steam it. So the LUN holds more than ends up in the cup. Enough for a latte, a cappuccino, a matcha latte or two flat whites. For a jug you'll pick up every morning, that's the right size. Small enough to pour with control. Big enough for two.",
        "gebrauch_h": "Hiss, spin, pour.",
        "gebrauch_p": "Cold milk, cold jug. Steam on, a quiet hiss, then the milk starts to turn. When the body gets too warm to hold, it's ready. You feel it in your palm, not on the handle. One tap, a swirl until it shines. Then pour.",
        "gebrauch_link": "Step by step: milk and latte art",
        "pflege_h": "Dishwasher? Yes.",
        "pflege_p": "All four colours can go in, on the days when there's no time. If you like yours, rinse it by hand and give it a quick dry. That keeps the finish free of water marks for longest.",
        "wer_dach": "MUNICH · VIENNA",
        "wer_h": "Two people, one espresso machine per kitchen.",
        "wer_p": "MJØÅR is Thorsten and Jonah, father and son. Thorsten lives in Munich, Jonah in Vienna, and at weekends Jonah works behind the counter of a Viennese café. That's where the LUN spent several weeks in daily use before we sold a single one.",
        "wer_link": "How the LUN came about",
        "aus_h": "Cardboard, cotton, jug. No plastic in between.",
        "aus_p": "The LUN comes in a natural cardboard box with a seal, wrapped in a cotton bag. That makes it a good gift. And if it stays with you, the bag still has a job to do.",
        "ausblick": "Coming next: glasses and cups. We're working on them.",
        "dach": "LUN · MILK JUG · 350 ML",
        "titel": "LUN 350",
        "absatz": "A milk jug made from one millimetre of stainless steel, with a narrow spout for latte art and a scale inside. All four matt, Steel as brushed stainless steel.",
        "punkte": ["Spout for hearts, tulips, rosettas", "Scale inside, ml and oz, laser engraved", "Dishwasher safe, every colour"],
        "farbwahl": "Colour",
        "detail": [
            ("The spout.", "In latte art, the last few centimetres between jug and cup matter more than the machine. The LUN's spout is narrow and rounded at the tip. Milk leaves it as a calm ribbon, not a gush. Hold it close to the surface and the milk settles on top. Lift it at the end and the stream breaks off cleanly. That's all a heart needs.", "detail-ausguss"),
            ("The wall.", "One millimetre of 304 stainless steel, for the whole jug, handle included. Many jugs this size are thinner. You notice when you grip them. The LUN doesn't give. It has some weight, which helps when pouring because your hand shakes less. Tap it on the worktop after steaming to pop the big bubbles and it sounds solid, not tinny.", "detail-wand"),
            ("The warmth.", "Steel conducts heat. Here that's useful: the body tells you how hot the milk is. When it's too warm to hold, it's done. The handle stays comfortable.", "gebrauch-aufschaeumen"),
            ("The scale.", "Laser engraved inside, in millilitres and ounces. It helps you repeat yourself: same amount, same result. And because it sits in the steel, it survives every dishwasher.", "detail-skala"),
            ("The finish.", "Juniper, Linen and Onyx have a matt coating. Steel is finely brushed stainless steel. Both show far fewer fingerprints than polished steel, and both look calmer next to a machine.", "detail-griff"),
        ],
        "entstehung_h": "Three rounds of samples. One colour fewer.",
        "entstehung_p": "First it was about colour. Then the dishwasher, because a good coating is worthless if it fades after a few weeks. A blue sample didn't hold up well. So there's no blue. After that, the LUN spent several weeks in daily use in a Vienna café, behind the counter with Jonah. Packaging came last, without plastic.",
        "daten_h": "Specifications",
        "daten": [("Capacity", "350 ml"), ("Material", "304 stainless steel, whole jug"), ("Wall", "1 mm"),
                  ("Finish", "Juniper, Linen, Onyx matt coated; Steel brushed"), ("Scale", "inside, laser engraved, ml and oz"),
                  ("Height / top / base", "9.3 / 6.4 / 7.5 cm"), ("Weight", "198 g"), ("Dishwasher", "yes, all colours"),
                  ("Hob, induction, microwave", "no"), ("Food contact", None)],
        "lfgb_platzhalter": "to follow",
        "daten_klein": "Measured by hand, small deviations are possible.",
        "box_h": "In the box and care",
        "box": [("In the box:", "the LUN in a cotton bag, in a natural cardboard box with a seal. No plastic."),
                ("Care:", "dishwasher safe. Rinsed by hand and dried, the finish stays free of water marks for longest. No abrasive cleaners, no steel wool.")],
        "pdf_zeile": "Safety information as PDF:",
        "pdf_link": "Safety information (PDF)",
        "fragen_h": "Questions",
        "fragen": [
            ("Can the LUN go in the dishwasher?", "Yes, all four colours. Rinsed by hand and dried, it stays looking its best for longest."),
            ("How much does it hold?", "350 ml. Enough for a latte, a cappuccino, a matcha latte or two flat whites, because milk needs room to grow."),
            ("Does it work with oat drink?", "Yes. Barista versions of oat or soy hold their foam best."),
            ("Does the handle get hot?", "You feel the warmth on the body. The handle stays comfortable."),
            ("Can I heat milk in it?", "No. Not on the hob, not on induction, not in the microwave. The LUN is made for steaming under the wand."),
            ("Why no blue?", "A blue sample didn't hold up well in our dishwasher tests."),
            ("Where does the name come from?", "From mjølk, Norwegian for milk, and å, the word for a small river. Milk that flows. Like when you pour."),
        ],
        "schluss": ("Enjoy your LUN.", "Thorsten and Jonah"),
        "la_dach": "A LITTLE COFFEE KNOW-HOW",
        "la_h": "Milk and latte art.",
        "la_intro": "Good milk for latte art looks like wet paint. Glossy, fine, no visible bubbles. Five steps get you there. The rest is practice, and the best time for that is every morning.",
        "la_schritte": [
            ("Start cold.", "Cold milk, ideally a cold jug too. The longer the milk takes to warm up, the finer the foam. Don't fill it too high. The milk needs room to rise."),
            ("Stretch.", "Steam wand just below the surface, steam on. A quiet, even hiss means air is going in. Only a few seconds. If it sounds like tearing, the wand is too high."),
            ("Spin.", "Wand a little deeper, jug slightly tilted. The milk starts to turn and pulls the big bubbles down, where they break up. Put your hand on the body. When it's too warm to hold, steam off."),
            ("Tap and swirl.", "One short tap on the worktop to pop the last bubbles. Then swirl until the surface shines like lacquer."),
            ("Pour.", "Start from a little height into the middle of the cup so milk and espresso blend. Then come close, spout almost touching the surface. Now the milk stays on top and the pattern appears. Finish by lifting and pulling through once."),
        ],
        "la_fehler_h": "Common mistakes:",
        "la_fehler": [("Big bubbles?", "Too much air, or spun too late."), ("Milk sinks?", "Spout too high."),
                      ("Pattern spreads?", "Milk too thin, stretch a little longer next time.")],
        "la_schluss": "The first heart is rarely pretty. The tenth usually is.",
        "la_drei_h": "Three drinks, one jug",
        "la_drei": [("Flat white:", "double espresso, a little very fine milk. One LUN makes two."),
                    ("Cappuccino:", "more foam, same cup. One LUN, one cappuccino."),
                    ("Matcha latte:", "whisk matcha smooth with a little hot water, then pour steamed milk over it. Works the same with cocoa.")],
        "ueber_dach": "MUNICH · VIENNA",
        "ueber_h": "Thorsten and Jonah.",
        "ueber_p": [
            "Father and son. Thorsten grew up in Vienna and lives in Munich. Jonah grew up in Munich and lives in Vienna. Both start the day at an espresso machine, and when they travel, the first stop is usually a café.",
            "The jugs we knew looked like tools. Thin metal, weld points on the handle, a high shine straight out of a commercial kitchen. Next to a good machine they never looked right. So we drew one that does.",
            "Three rounds of samples later, after several weeks in daily use in a Vienna café and packaging without any plastic, there was the LUN. We built the name MJØÅR from two words: mjølk, Norwegian for milk, and å, a small river. It sounds Scandinavian. It's made for kitchens in Munich, Vienna and anywhere else.",
            "We design things for coffee, matcha and hot chocolate. Good materials, a fair price, nice enough to give away. Glasses and cups come next.",
            "MJØÅR is small. Which means: when you write to us, we answer ourselves. info@mjoar.com",
        ],
        "meta": {
            "start": ("MJØÅR · LUN stainless steel milk jug", "The LUN 350: one millimetre of stainless steel, a spout for latte art, matt colours. By Thorsten and Jonah from Munich and Vienna."),
            "lun": ("LUN 350 milk jug · MJØÅR", "350 ml, scale inside, dishwasher safe. In Juniper, Linen, Onyx and Steel."),
            "latte": ("Steaming milk and latte art · MJØÅR", "Five steps to glossy milk and your first heart. Plus flat white, cappuccino and matcha latte."),
            "ueber": ("About · MJØÅR", "Thorsten and Jonah, father and son from Munich and Vienna, and how the LUN came about."),
            "impressum": ("Imprint · MJØÅR", None),
            "datenschutz": ("Privacy · MJØÅR", None),
        },
    },
}

# Alt-Texte und Bedienetiketten: nicht in der Copy, nötig für Barrierefreiheit (WCAG 1.1.1, 4.1.2).
# Kein Maschinen-Schriftzug, keine fremden Marken (Auftrag 07.10.).
ALT = {
    "de": {
        "hero": "LUN 350 in Juniper an der Siebträgermaschine",
        "hero_0284": "Die LUN in vier Farben",
        "farbe": "LUN 350 in {}",
        "detail-ausguss": "Tülle der LUN", "detail-wand": "Rand der LUN in Juniper", "detail-skala": "Skala innen in ml und oz",
        "detail-griff": "Griff und Oberfläche der LUN in Linen",
        "groesse": "LUN in Linen beim Gießen, in der Hand",
        "gebrauch-aufschaeumen": "Milch aufschäumen mit der LUN in Juniper", "gebrauch-giessen": "Gießen mit der LUN in Onyx",
        "gebrauch-tasse": "LUN in Onyx neben einem Cappuccino",
        "verpackung": "LUN in {} mit Baumwollbeutel und Naturkarton",
        "familie": "Die LUN in vier Farben",
        "latte": {"heart": "Latte Art Herz", "rosetta": "Latte Art Rosetta", "tulip": "Latte Art Tulpe", "swan": "Latte Art Schwan"},
        "menu": "Menü", "start": "MJØÅR Startseite", "sprache": "Sprache",
    },
    "en": {
        "hero": "LUN 350 in Juniper at an espresso machine",
        "hero_0284": "The LUN in four colours",
        "farbe": "LUN 350 in {}",
        "detail-ausguss": "Spout of the LUN", "detail-wand": "Rim of the LUN in Juniper", "detail-skala": "Scale inside in ml and oz",
        "detail-griff": "Handle and finish of the LUN in Linen",
        "groesse": "LUN in Linen while pouring, in the hand",
        "gebrauch-aufschaeumen": "Steaming milk with the LUN in Juniper", "gebrauch-giessen": "Pouring with the LUN in Onyx",
        "gebrauch-tasse": "LUN in Onyx next to a cappuccino",
        "verpackung": "LUN in {} with cotton bag and cardboard box",
        "familie": "The LUN in four colours",
        "latte": {"heart": "Latte art heart", "rosetta": "Latte art rosetta", "tulip": "Latte art tulip", "swan": "Latte art swan"},
        "menu": "Menu", "start": "MJØÅR home", "sprache": "Language",
    },
}

# Für den Wortgleichheits-Diff: Seitentext, der bewusst nicht aus der Copy stammt.
NICHT_IN_COPY = {
    "de": ["folgt"],
    "en": ["Specifications", "In the box and care", "Questions", "to follow"],
}
